### ISSUE TITLE
Log percentage of covered methods per PDB in debug mode

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-profiler-dotnet#104]
This could help debugging missing coverage/incorrect configuration

**Comment by salsolatragus** [comment]
@karottenreibe aren't we doing this already? I seem to remember many (0/n) messages in the logs.

**Comment by karottenreibe** [comment]
These are "X of Y" where Y is the number of methods mentioned in the trace file, not the number of methods in the PDB file (i.e. methods that are never executed are not counted in this). So the percentage we show right now is really hard to interptet (did we not cover anything from the PDB or are just all of the 5 executed methods compiler-generated and not interesting?)

**Comment by karottenreibe** [comment]
Migrated as TS-21305
