### ISSUE TITLE
Batch upload of coverage

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-profiler-dotnet#110]
When processing coverage, the uploader should batch uploads to Teamscale as much as possible to avoid having 100s of small uploads when one big one would do.

When implementing this, we will probably need to cache coverage on disk because multiple processes might be profiled wtih different partitions, revision.txt contents etc.

**Comment by karottenreibe** [comment]
I already wrote some code. Before you also do, let's synchronize @salsolatragus

**Comment by salsolatragus** [comment]
Hm... the I hope we did different, compatible things... my stuff is [here](https://github.com/cqse/teamscale-profiler-dotnet/tree/110_batch_upload). Time for a call tomorrow morning?

**Comment by karottenreibe** [comment]
yes, we definitely need to sync. I think we tried to solve the same problem but with wildly different approches ;-) Let's decide which one we want to finish tomorrow. Can you send me a calendar invite please (I'm already on the train ;-)) Thanks!
