### ISSUE TITLE
Allow dumping coverage while application is running

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-profiler-dotnet#113]
Before working on this issue, please consult with @karottenreibe, @agoeb  and @DreierF 

We need to consider

- how this interacts with TIA
- how the Upload Daemon is supposed to handle this coverage

**Comment by salsolatragus** [comment]
Can you elaborate a little more on what's the expected benefit is? What's our use case?

**Comment by agoeb** [comment]
@salsolatragus Similar to our JaCoCo agent, the use case is especially related to long-running processes, e.g. web servers. So when you run your web application in IIS, you may not want to recycle the application pool on a regular basis, just to get coverage out. Restarting a process will interrupt ongoing activities and may trigger additional shutdown or startup actions unnecessarily.

Currently, we can use the eager mode to write coverage to the file, but we always continue writing the same file and do not start a new one that we could upload separately. I guess the idea is that we can write a complete file at specified intervals (or somehow event-triggered) and then start a new one, just as if you restarted the process, but without actually doing so.

**Comment by karottenreibe** [comment]
exactly. plus: TIA needs this as well

Andreas Goeb <notifications@github.com> schrieb am Di., 14. Mai 2019, 08:36:

**Comment by karottenreibe** [comment]
Migrated as TS-21168
