### ISSUE TITLE
Configure upload interval and allow one-shot uploads

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#115]
It would be nice if one could configure the upload interval to something else than 5 minutes and also to switch it off completely, which equals to upload on demand (note that this is different from enabling/disabling the daemon invocation from the profiler!).

**Comment by karottenreibe** [comment]
In addition: provide a way to start the upload daemon in one-shot mode (i.e. perform one upload, then shut down)
