### ISSUE TITLE
Consider environment variables in uploader config

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#116]
We can set the profiler's trace path through an environment variable, which is convenient if the directory is dynamically created at runtime (e.g., in a CI environment). However, there is currently no way to have the Uploader scan an a-priori unknown directory (without dynamically writing configs...). It would be nice if the Uploader could replace Env-Variables in the config file or something...

**Comment by karottenreibe** [comment]
Since you already outlined the alternative in a recent mail: Users can modify the config themselves with a script before starting an upload. I don't think making our config parsing more complicated is necessary here.
