### ISSUE TITLE
Problems with Inter-process communication

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#122]
We're using Named Pipes for inter-process communication between `UploadDaemon` instances. Using these pipes may be disabled, such that processes cannot talk to one another.  We've decided before that we want to stick with Named Pipes (#92), however, it would be nice if the daemon could recognize that pipe usage is restricted and act accordingly, e.g., log the problem and shut down, because currently there's just an growing number of processes waiting for a response over the pipe...

We had one customer where the number of daemons simply exploded, because every invocation from the profiler spawned a new process (CPU load spiked here!). In another case, it seems only one daemon per profiled process is started (may a different pipe-restriction level?).

We need to decide what the fallback behavior should be.

**Comment by karottenreibe** [comment]
@salsolatragus if this can be detected easily, I'd like the daemon to stop and log an error. The error message should include simple instructions for the user to "install the daemon as a service or run it once manually after all tests are done" and reference the documentation. I don't think we need any other fallback here.

**Comment by karottenreibe** [comment]
@salsolatragus another problem that we just had that I hadn't even thought about until now: if you start several processes but under different users, these apparently can't always talk to each other. E.g. Windows service + GUI app

**Comment by karottenreibe** [comment]
Migrated as TS-21163
