### ISSUE TITLE
Allow duplicated PDBs

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#127]
Apparently, a .NET may output multiple copies of the same PDB file, if the same assembly is referenced by multiple components. The copies then appear in subdirectories of “the” PDB directory. Currently, this makes our conversion fail, because it does not know which PDB to chose. According to a customer, the MS tools are able to detect that all these PDBs are identical and just pick one. We should probably do the same.

**Comment by karottenreibe** [comment]
Migrated as TS-21155
