### ISSUE TITLE
UploadDaemon: allow running multiple daemons from different directories

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-profiler-dotnet#134]
In order to be able to upload to different destinations or use different PDB dirs, we should allow multiple UploadDeamon instances if and only if the exe is at a different location. Or in other words: only instances of the Daemon that are started from the same location on disk should talk to each other.

**Comment by salsolatragus** [comment]
Can't I specify different `uploader` configurations (and `targetdir`s) in the config sections dedicated to particular processes? What scenario can't we solve with this that could be solved with multiple processes?

Just looking whether there is a simpler solution for the same goal ;)

**Comment by karottenreibe** [comment]
good point. discarding
