### ISSUE TITLE
Cannot register Profiler with regsvr32

### ISSUE THREAD

**Issue by mpdeimos** [cqse/teamscale-profiler-dotnet#138]
When registering the current version of the profiler with regsvr32, it looks like we're writing to the registry under a gibberish key :/

This should be the CLSID of the profiler instead.

![image](https://user-images.githubusercontent.com/644735/63449438-76b47600-c440-11e9-82d7-09aae4124860.png)

**Comment by karottenreibe** [comment]
Migrated as TS-21152
