### ISSUE TITLE
Profiler.yml not loaded if profiler is registered via regsvr32

### ISSUE THREAD

**Issue by mpdeimos** [cqse/teamscale-profiler-dotnet#139]
If you register the profiler via regsvr32 the default `Profiler.yml` does not get loaded. This is because the position is determined relative to `COR_PROFILER_PATH` which is not set.

Expected behavior would be the to load the config file next to the DLL.

A workaround exists if you specify the config file as environment variable.

![image](https://user-images.githubusercontent.com/644735/63467874-baba7180-c466-11e9-9e21-ce042a9b7bea.png)

**Comment by karottenreibe** [comment]
Migrated as TS-21151
