### ISSUE TITLE
Make VersionAssembly optional when using Directory upload

### ISSUE THREAD

**Issue by mpdeimos** [cqse/teamscale-profiler-dotnet#140]
Specifying the version assembly is redundant if you already separate traces by executable path/name, and raised a few problems for users like traces not being copied, ...

In my opinion we should make the versionAssembly optional if you do not upload to Teamscale directly. If we specify it filtering should work the same way as right now.

---

@salsolatragus: The version assembly is currently only required when uploading raw method coverage (regardless of the target). When we convert to line coverage locally before upload, we don't consider the version assembly at all. The documentation currently doesn't reflect this. Please update on the go.

**Comment by salsolatragus** [comment]
Does it make sense to simply make the version assembly completely optional? After all, if I make it optional when an exe path is present, I can specify the path `.*` to trace everything and not filter at all... The assembly would then become simply a filter _option_...

**Comment by salsolatragus** [comment]
Removing it completely would be my favorite solution :D

**Comment by mpdeimos** [comment]
I work around this by specifying mscorlib as version assembly and filter afterwards when the trace has reached the Teamscale server

**Comment by karottenreibe** [comment]
Discarding as solution is to migrate to new profiler with local PDB conversion
