### ISSUE TITLE
Improve handling of incorrectly set up urls

### ISSUE THREAD

**Issue by AnonymFx** [cqse/teamscale-profiler-dotnet#144]
I just spent a couple of hours debugging the upload daemon when the problem was an incorrectly configured URL, i.e. I forgot the Teamscale URL prefix. Reproducing the problem with Insomnia showed, that Teamscale actually returns a 500 after 30s and it would have been very helpful if this had shown in the log.
So my suggestion is: log some kind of error message in the log and ask the user if he might have forgotten the URL prefix. 
Note: I also created an [Issue for Teamscale](https://jira.cqse.eu/browse/TS-20324) asking to improve the returned error, so we might be able to react to a different, more clear error code in the future.

**Comment by karottenreibe** [comment]
Migrated as TS-21150
