### ISSUE TITLE
Upload coverage reports from share to Teamscale

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#148]
A customer tests on many machines in parallel (same version of their product).

When they upload from each machine directly to Teamscale, they get lots of rollbacks and tons of redundant coverage data.

When they upload to a share and publish the reports from there, they solve the rollback issue, but they still have redundant data.

Our answer to the redundancy problem on a single machine is to merge the coverage reports before upload.

Since they have multiple machines and only consolidate the reports on the share, they can't use this feature out of the box. Would be nice if they could use the UploadDaemon to merge and upload the reports from the share (read .simple and .metadata files, merge, upload).

**Comment by karottenreibe** [comment]
The same customer asked for a command line interface to be able to run the "Deamon" on-demand from scripts. Maybe for such a compilcated use case this is indeed the better option, which we'll be able to reuse for more customers. Something like:

```sh
UploadDeamon.exe --merge file1.simple file2.simple file3.simple
```

For the upload to Teamscale, I still think it makes more sense to use either curl or the existing python scripts than to again duplicate this functionality in a third tool here.

**Comment by salsolatragus** [comment]
Since the daemon can already do the upload, I don't see why we shouldn't reuse this functionality for this scenario, because it would allow us to solve the use case with a single tool.

Regarding merge, I would suggest to go one step further and provide something like

```
UploadDaemon.exe --merge C:\path\to\coverage
```

and have the Daemon create the possible batches from all the files in the directory.

**Comment by karottenreibe** [comment]
What would the upload command look like?

```sh
UploadDaemon.exe --upload teamscale-url --project project --partition "Manual Test" C:\path\to\coverage
```

Whether coverage can be merged depends on a) the revision.txt content and b) the target of the upload (Teamscale URL + project + partition). We currently only store the revision.txt content together with each coverage file. So merging cannot happen purely automatically unless we always merge everything in the folder recursively. Is that what you meant? I.e. the users have to sort by upload target themselves, each target with a separate folder, and then we merge everything in that folder recursively? That would work IMO.

**Comment by salsolatragus** [comment]
We could even use an `UploadDaemon.yml` with the same format as the uploader sections in the `Profiler.yml`?

And yes, I would assume that everything in the same folder goes to the same upload target (TS+project+partition). The revision info is in the metadata file, so we can group by that. I think this is reasonable to ask, because we can easily specify a distinct path for each share upload in the `Profiler.yml` on the original testing machines.

**Comment by karottenreibe** [comment]
Migrated to TS-21147
