### ISSUE TITLE
Incorrectly formatted profiler.yml should log error and stop profiler/uploader

### ISSUE THREAD

**Issue by acidg** [cqse/teamscale-profiler-dotnet#149]
I had this several times now: tabs instead of spaces or incorrect indentation. The profiler then sometimes is running with defaults (e.g. using C:\Users\Public as TargetDir which may be confusing for the user. Better would be to exit the profiler and log the parsing issue.

**Comment by karottenreibe** [comment]
Migrated as TS-21304
