### ISSUE TITLE
Profiling if one process starts another one

### ISSUE THREAD

**Issue by stefansta1** [cqse/teamscale-profiler-dotnet#177]
Our software starts one process from another process like 
Info=Command Line: "C:\Program Files\..\Program1.exe" --use-rest-configuration --start "C:\Program Files..\Program2.exe". The first process Program1 checks if updates are available and starts the second process. The teamscale-profiler-dotnet is not able to trace the second Program2 process. If the Program2 is started seperately the process can be correctly traced.

**Comment by snowbagoly** [comment]
Thank you for reporting this issue! Unfortunately I could not reproduce it locally: in my setup the profiler profiled both executables, creating two separate coverage files. Could you please provide some more information?

1. Could you provide an example file for starting the second process? I used the `System.Diagnostics.Process` class without any special settings.
2. Do you wait in the main process for the second process to finish? This might result in a delay between printing the coverage file for the first process and the second process, as at latest we dump all coverages when the process finishes.
3. Could you also provide the `Profiler.yml` configuration that you used?

Thank you in advance!

**Comment by karottenreibe** [comment]
@stefansta1 one thing you can try is to run both processes and then inspect the second process that is not being profiled with the MS process explorer https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
This will show you the environment variables the second process sees. My guess is that the way you start the second process from the first removes the relevant environment variables and thus it isn't profiled.

If none of the above suggestions work, can you please contact us at support@teamscale.com, then we can do some more in-depth debugging together with you.

**Comment by stefansta1** [comment]
I changed the starting proces and it work now
