### ISSUE TITLE
documentation.md should be called README.md

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-profiler-dotnet#36]
Then GitHub will render it automatically when you view the documentation folder

**Comment by salsolatragus** [comment]
Is this still relevant? There's only a `documentation/userguide.md`, which seems to have been migrated (in part) to the GitHub Wiki (or the other way around?).

Cleaning up the redundant documentation seems worthwhile, but should it be in the repo or in the wiki?

**Comment by salsolatragus** [comment]
@karottenreibe is this still relevant? See my comment above.

**Comment by karottenreibe** [comment]
I think I'll make a new issue with my current plans for the documentation, which at the moment are only in my head. Then we can discuss them there. I'll CC you.
