### ISSUE TITLE
Figure out how to make debugging the profiler easier

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-profiler-dotnet#40]
Can we somehow attach with a debugger? If not, what are alternatives?

**Comment by salsolatragus** [comment]
I explored two approaches, the second of which did work for me. @karottenreibe @mpdeimos does this solution work for you, or should we try to get this to work in Visual Studio?

## Attach to Process

Scott Hackett [explains how to create a profiler](https://www.codeproject.com/Articles/15410/Creating-a-Custom-NET-Profiler) and notes he hasn't found a way to attach a debugger to it (all debugging via log output).

* One comment states one should simply attach a debugger to the target process, but this didn't work for me.
* Another comment references a [MSDN Magazine Issue](http://msdn.microsoft.com/en-us/magazine/cc188781.aspx) on the matter, which is unfortunately no longer available at this address.

## WinDbg

David Broman [explains how to debug profilers using `windbg`](https://blogs.msdn.microsoft.com/davbr/2007/12/11/debugging-your-profiler-i-activation/). With the following script I could successfully debug the profiler with `windbg` on Windows 10 (with the Windows SDK installed):

    SET COR_ENABLE_PROFILING=1
    SET COR_PROFILER={DD0A1BB6-11CE-11DD-8EE8-3F9E55D89593}
    SET COR_PROFILER_PATH=E:\Profiler\bin\Debug\Profiler64.dll

    "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" "E:\test-data\test-programs\GeneratedTest.exe"

When `windbg` starts up, hit 'Insert and remove breakpoints' (`F9`) and add a breakpoint to

    bu Profiler64!CProfilerCallback::Initialize

Then hit 'Go' (`F9`). The program will stop at the invocation of our initialization and open a source view showing this location. From this point you can debug with step over/into/out as usual.

### Notes

* In the above setting on my machine, `windbg` finds the source files automagically. If it doesn't in some other setting, setting `File > Source File Path...` probably helps.
* You can set more specific breakpoints. Microsoft provides [a guide explaining the breakpoint syntax](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/breakpoint-syntax).

**Comment by salsolatragus** [comment]
@karottenreibe @mpdeimos any thoughts on the above procedure?

**Comment by salsolatragus** [comment]
@karottenreibe @mpdeimos any thoughts on the above procedure?

**Comment by karottenreibe** [comment]
@salsolatragus sounds good. I think you should persist it in the repo somewhere (DEBUGGING.md?)

**Comment by salsolatragus** [comment]
Will do.

**Comment by salsolatragus** [comment]
Done: https://github.com/cqse/teamscale-profiler-dotnet/blob/master/documentation/CONTRIBUTE.md
