### ISSUE TITLE
Improve installation guide

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#45]
When I tried to run an app with the profiler, I first expected the traces to show up in `C:\Users\Public\Traces`, because this is the path [mentioned in the installation guide](https://github.com/cqse/teamscale-profiler-dotnet/wiki/Installation#registering-the-profiler-for-the-target-application). I was confused by no traces being generated and it took me a while to realize that the default path is actually `C:\Users\Public` (as correctly documented on the configuration-file page and in the beginning of the installation page).

I think we should either use the default path in the instructions as well or list the configuration option for changing it in the table. Since the guide explicitly talks about creating and sharing (whatever the latter implies...), I'm not sure which one you consider the better option. Otherwise, I'm happy to just do this change ;)

**Comment by karottenreibe** [comment]
Migrated as TS-21149
