### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#48]
Currently, the project does not adhere to the CQSE coding guidelines. @mpdeimos suggested to use this opportunity to evaluate alternative code formatters (e.g., VS Internal, EditorConfig, CodeMaid) and chose the best tool to use throughout CQSE projects.

## VS Internal

* Doesn't support auto formatting. Extensions that add this feature are:
    * [Productivity Power Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017)
    * [Format Document on Save](https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave)
    * [CodeMaid](#CodeMaid)
* Doesn't allow repo-based sharing -> use [EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017)

## CodeMaid

* Uses VS Internal formatting, hence, we'd probably need both configurations.
* Supports auto formatting on save.
* Supports auto formatting the entire codebase at once, allowing exclusion of (generated) files.
* Supports [solution-specific configuration (repo-based sharing)](http://www.codemaid.net/2015/07/19/codemaid-v0-8-0-solution-specific-settings-released/). By default, only a diff to the user's default settings is stored, but we could manually generate a full configuration from [the app default configuration](https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/app.config).

**Comment by karottenreibe** [comment]
Decision: use new .editorconfig support of VS https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019

**Comment by karottenreibe** [comment]
Migrated as TS-21310
