### ISSUE TITLE
Invalid UploadDaemon path in .NET Core environment

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#65]
To determine the path to `UplaodDaemon.exe` the profiler [uses the `PATH` environment variable](https://github.com/cqse/teamscale-profiler-dotnet/blob/f5b8a1adcca3d579ae83782ff039432a5054317b/Profiler/CProfilerCallback.cpp#L103), which translates to `COR_PROFILER_PATH` under the hood. When profiling .NET Core apps, however, we configure the profiler path through the `CORECLR_PROFILER_PATH_X` variables and `COR_PROFILER_PATH` may not be set. The base path for the `UploadDaemon.exe` then resolves to empty string and we end up with the path `\UploadDaemon\UploadDaemon.exe`, which does not exist. The invocation of this non-existent executable crashes the profiler without log message.

Expectation:

* The profiler should consider both the `COR_` and `CORECLR_` variables to determine the path.
* The profiler should check whether the executable exists and output a proper error message if not.

**Comment by karottenreibe** [comment]
Migrated as TS-21309
