### ISSUE TITLE
Unify versioning info across subprojects

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#67]
Currently, the Profiler, the GUI, and the UploadDaemon separately manage version information. [As we started to discuss](https://github.com/cqse/teamscale-profiler-dotnet/pull/19#discussion_r237517254) it would be great to store this information in a single place and  reference it from there, to ensure that all parts of the profiler are in sync.

**Comment by karottenreibe** [comment]
GUI was deleted
