### ISSUE TITLE
Profiler GUI/Daemon: Create "UploadDaemon" folder if needed

### ISSUE THREAD

**Issue by Dan1ve** [cqse/teamscale-profiler-dotnet#87]
It seems that trying to upload traces with the Daemon  only works if you manually create  the "UploadDaemon" folder, which is cumbersome. The daemon should simply create the folder itself, if necessary.

**Comment by karottenreibe** [comment]
Can you please share some screenshots? That folder exists in the newest distribution zip. Was this with the newest version?

**Comment by karottenreibe** [comment]
@Dan1ve can you comment on my question? do you still know why that folder was missing or give additional context?

**Comment by salsolatragus** [comment]
Probably won't fix due to #136

**Comment by karottenreibe** [comment]
discarding for this reason
