### ISSUE TITLE
Communication of Named Pipes may be restricted

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#92]
Currently, the UploadDaemon communicates over Named Pipes to delegate an upload command to the single acting daemon instance. If machine‘s policy [restricts communication over Named Pipes](https://docs.microsoft.com/en-us/windows/desktop/ipc/named-pipe-security-and-access-rights) this does not work.

We observed on a customer machine that tens of daemon processes remained open and consumed considerable system performance. This may be related.

**Comment by karottenreibe** [comment]
Solution is to run the daemon as a windows service and set upload_daemon=false in the config
