### ISSUE TITLE
Log "Attached to X" from the profiler

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#97]
It would be nice to have some log that shows to which processes the profiler attached, for debugging purposes. E.g., we could introduce a configuration option to set a log path and, if this path is specified, log attach events to this location (while otherwise logging nothing).

**Comment by karottenreibe** [comment]
We should log both the Process path (C:\some.exe) and the PID of the process to uniqely identify it.
The log file should be located next to the .yml config file of the profiler. The log path does not need to be configurable.

**Comment by karottenreibe** [comment]
In case the log file is not writable, the profiler should just not write the log but function normally otherwise.

**Comment by karottenreibe** [comment]
Migrated as TS-21153
