### ISSUE TITLE
Revise docu to a more instructive style for new users

### ISSUE THREAD

**Issue by salsolatragus** [cqse/teamscale-profiler-dotnet#98]
When I install the profiler (for the first time), I want to have introductions that I can follow step by step, rather than a reference containing all information I might ever need. This should contain the happy path plus common caveats. All special cases should go into a troubleshooting section.

The introduction should include:

* validation steps for a correct setup (e.g., check trace files are created on target-process start, coverage is appended on target-process termination, UploadDaemon process is started, UploadDaemon writes log, UploadDaemon moves coverage files, ...) with links to respective troubleshooting steps
* which directories the profiler/UploadDaemon need read/write access to.
* a script to set to required environment variables via `setx /m var val` commands.
* a hint to reboot the process-to-profile or the entire machine, to ensure the process has the required environment variables loaded

Toubleshooting should include:

* a hint to check the environment variables for the target process through the Task Manager
* a hint to check the Event Log for problems 
* usage of the Native Image Cache

**Comment by karottenreibe** [comment]
Migrated as TS-21306
